export const CHANGE_VIEW = 'CHANGE_VIEW';
export const POST_TEXT_ENTRY = 'POST_TEXT_ENTRY';
export const RECEIVE_TOKENS = 'RECEIVE_TOKENS';
export const RECEIVE_TEXT_ENTRY = 'RECEIVE_TEXT_ENTRY';
export const RECEIVE_FEED = 'RECEIVE_FEED';
export const INVALIDATE_TEXT_ENTRY = 'INVALIDATE_TEXT_ENTRY';
export const SELECT_ENTRY = 'SELECT_ENTRY';
